trigger:
- main  # or any branch you want to trigger the pipeline

variables:
  terraformVersion: '1.4.6'  # Specify the Terraform version you want to use
  workingDirectory: 'terraform'  # Path to your Terraform configuration files
  azureServiceConnection: 'SC_for_Terraform_Ramesh'  # Name of your Azure Service Connection

jobs:
- job: Terraform
  pool:
    vmImage: 'ubuntu-latest'  # Use an Ubuntu-based VM

  steps:
  - task: UseTerraform@0
    inputs:
      versionSpec: $(terraformVersion)
    displayName: 'Install Terraform'

  - checkout: self
    displayName: 'Checkout code'

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptPath: $(System.DefaultWorkingDirectory)/path/to/your/script.sh
    displayName: 'Authenticate with Azure and Run Terraform'
