trigger:
- main  # or any branch you want to trigger the pipeline

variables:
  terraformVersion: '1.4.6'  # Specify the Terraform version you want to use
  workingDirectory: 'terraform'  # Path to your Terraform configuration files
  azureServiceConnection: 'SC_for_Terraform_Ramesh'  # Name of your Azure Service Connection

jobs:
- job: Terraform
  pool:
    vmImage: 'ubuntu-latest'  # Use an Ubuntu-based VM

  steps:
  - script: |
      # Install Terraform
      curl -LO https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
      unzip terraform_$(terraformVersion)_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform --version
    displayName: 'Install Terraform'

  - checkout: self
    displayName: 'Checkout code'

  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptPath: script.sh
    displayName: 'Authenticate with Azure and Run Terraform'
